### ISSUE TITLE
"Initialize Language Server" goes on forever

### ISSUE THREAD

**Issue by ddekany** [angelozerr/freemarker-languageserver#2]
On a new Photon M6 installation, if I open an `*.ftl` file, Eclipse shows "Initialize Language Server for test.ftl" in the lower right corner, with the progress bar animation, and that goes on forever. Thus there's no LSP4E related functionality in the editor.

In the error log I find this:

```
!ENTRY org.eclipse.lsp4e 4 0 2018-03-17 19:06:56.505
!MESSAGE LanguageServer not initialized after 10s
!STACK 0
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.eclipse.lsp4e.LanguageServerWrapper.getServerCapabilities(LanguageServerWrapper.java:526)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrappers(LanguageServiceAccessor.java:281)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfosFor(LanguageServiceAccessor.java:395)
	at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$1.run(ConnectDocumentToLanguageServerSetupParticipant.java:74)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

So it's two problems:
- The language server initialization fails
- If the language server initialization fails, I should get some kind of error indicator, and the progress indicator should stop.

**Comment by angelozerr** [comment]
I close the issue because it's an issue for lsp4e freemarker. I have recrated the issue at https://github.com/angelozerr/lsp4e-freemarker/issues/2
